version : "3.3"
services:
    adipem-api:
        build: .
        ports:
            - "8080:80"
        environment: 
            DbServer: ms-sql-server
    ms-sql-server:
        container_name: ms-sql-server
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
            - "1433:1433"
        environment:  
            SA_PASSWORD: "reallyStrongPwd123"
            ACCEPT_EULA: "Y"
            MSSQL_PID: Express